import { useContext } from "react";
import Head from "next/head";

import Details from "@/components/template/details";

export default function Index() {
  return (
    <>
      <Head>
        <title>Mercado Livre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://http2.mlstatic.com/frontend-assets/ml-web-navigation/ui-navigation/5.21.22/mercadolibre/favicon.svg"
          rel="icon"
          data-head-react="true"
        />
      </Head>
      <main>
        <Details />
      </main>
    </>
  );
}
